server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    bus-env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

